name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build и Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/hello_word:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Добавить SSH-ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name:  deploy.sh на сервер
        run: |
          scp ./deploy/deploy.sh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/tmp/deploy.sh

      - name:  deploy.sh по SSH
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "export DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/hello_word:latest && bash /tmp/deploy.sh"

      # Ansible 
      # - name:  Установить Ansible
      #   run: |
      #     sudo apt update
      #     sudo apt install -y ansible

      # - name: Выполнить Ansible Playbook
      #   run: |
      #     ansible-playbook deploy/ansible/playbook.yml -i "${{ secrets.REMOTE_HOST }}," \
      #       --user ${{ secrets.REMOTE_USER }} --private-key ~/.ssh/id_rsa
